version: '3'
services:

  node1:
    image: nodejs-blockchain/node1
    container_name: nodejs-blockchain-node1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3001:3001"
    volumes:
      - ./:/usr/src

  node2:
    image: nodejs-blockchain/node2
    container_name: nodejs-blockchain-node2
    environment:
      - PEERS=ws://node1:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3002:3001"
    volumes:
      - ./:/usr/src
    links:
      - node1:node1

  node3:
    image: nodejs-blockchain/node3
    container_name: nodejs-blockchain-node3
    environment:
      - PEERS=ws://node2:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3003:3001"
    volumes:
      - ./:/usr/src
    links:
      - node2:node2

